[package]
name = "fuchsian"
version = "0.0.1"
edition = "2021"
author = "snusnu (Steffen)"
description = "Fuchsian and hyperbolic geometry"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
